cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import board.views
import users.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', board.views.home),
    path('popup/popup1.html', board.views.popup),
    path('popup/event1.html', board.views.popup1),
    path('popup/event2.html', board.views.popup2),
    path('popup/event3.html', board.views.popup3),

    path('board/', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('login/', users.views.userlogin),
    path('logout/', users.views.userlogout),
    path('kakao_logout', users.views.kakao_logout),
    path('signup/', users.views.signup),

    path('mypage/', include('users.urls')),
    path('board/', include('board.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('shop/', include('shop.urls')),



    # path('question/', board.views.q_index, name='q_index'),
    # path('question/<int:question_id>', board.views.detail, name='detail'),
    # path('answer/create/<int:question_id>', board.views.answer_create, name='answer_create'),


]

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name = 'coupon'

urlpatterns = [
    path('add/', add_coupon, name='add'),
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),

]

shop/urls.py
from django.urls import path
from .views import *


app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('<int:id>/<product_slug>/add_comment', add_comment, name='add_comment'),
    path('<int:bid>/<product_slug>/like', like, name='like'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    labels = {
        'quantity': '수량',
    }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

# Create your views here.

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart
from coupon.forms import AddCouponForm

@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

        return redirect('cart:detail')

def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()

    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity': product['quantity'], 'is_update': True})

    return render(request, 'cart/detail.html', {'cart': cart, 'add_coupon':add_coupon})

templates/cart/detail.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
{% if request.user.is_authenticated %}
<div class="page_aticle aticle_type2">
    <div id="snb" class="snb_my">
        <h2 class="tit_snb">마이컬리</h2>
        <div class="inner_snb">
            <ul class="list_menu">
                <li class="on">
                    <a href="/mypage">장바구니</a>
                </li>
                <li>
                    <a href="#none"
                       onclick="KurlyTrackerLink('/shop/mypage/mypage_pick.php', 'select_my_kurly_pick_list')">찜한 상품</a>
                </li>
                <li>
                    <a href="/shop/mypage/mypage_review.php">상품 후기</a>
                </li>
                <li>
                    <a href="/shop/mypage/product_inquiry.php">상품 문의</a>
                </li>
                <li>
                    <a href="/mypage/coupon"
                       onclick="">쿠폰</a>
                </li>
                <li>
                    <a href="/mypage/update">개인 정보 수정</a>
                </li>
            </ul>
        </div>
        <a href="/mypage/inquiry/form" class="link_inquire"><span class="emph">도움이 필요하신가요 ?</span> 1:1 문의하기</a>
    </div>
    <div id="viewOrderList" class="page_section section_orderlist">
        <div class="head_aticle"><h2 class="tit">장바구니 <span class="tit_sub">장바구니 조회가 가능합니다</span></h2></div>

<!--        <h1> 장바구니에 담긴 상품이 없습니다. </h1>-->

        <ul class="list_order">
            <table class="table table-striped" width="850">
                <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <th scope="row">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" class="thumb">
                        </a>
                    </th>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:product_add' product.id %}" method="post">
                            {{ item.quantity_form.quantity }}
                            {{ item.quantity_form.is_update }}
                            <input type="submit" class="btn btn-primary" value="수량 수정">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url 'cart:product_remove' product.id %}"><img
                            src="{% static 'image/x2.png' %}"></a></td>
                    <td class="num">{{ item.price }}원</td>
                    <td class="num">{{ item.total_price }}원</td>
                </tr>
                {% endwith %}
                {% endfor %}
                {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td>${{ cart.get_product_total }}</td>
                </tr>
                <tr>
                    <td>"{{ cart.coupon.code }}" coupon ({{ cart.coupon.amount }}원)</td>
                    <td colspan="4"></td>
                    <td>- {{ cart.get_discount_total|floatformat:"2" }}원</td>
                </tr>
                {% endif %}
                <tr class="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="num">{{ cart.get_total_price|floatformat:"2" }}원</td>
                </tr>
                </tbody>
            </table>
            &ensp;
            &ensp;
            &ensp;
            <div>
                <p>
                    쿠폰 등록하기:
                </p>
                <form action='{% url "coupon:add" %}' method="post">
                    {{ add_coupon }}
                    <input type="submit" value="Add">
                    {% csrf_token %}
                </form>

                <p class="text-right">
                    <a href="{% url 'shop:product_all' %}" class="btn btn-secondary">계속 쇼핑하기</a>
                    <a href="{% url 'order:order_create' %}" class="btn btn-secondary">결제하기</a>
                </p>
            </div>
        </ul>
    </div>

    {% endif %}
    {% endblock %}