board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    path('n/', views.n_index, name='n_index'),
    path('n/<int:notice_id>/', views.n_detail, name='n_detail'),
    path('n_answer/create/<int:notice_id>/', views.n_answer_create, name='n_answer_create'),
    path('notice/create/', views.n_question_create, name='notice'),
    path('notice/modify/<int:notice_id>/', views.n_question_modify, name='notice_modify'),
    path('notice/delete/<int:notice_id>/', views.n_question_delete, name='notice_delete'),
    path('n_answer/modify/<int:n_comment_id>/', views.n_answer_modify, name='n_answer_modify'),
    path('n_answer/delete/<int:n_comment_id>/', views.n_answer_delete, name='n_answer_delete'),
]

cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import board.views
import users.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', board.views.home),
    path('popup/popup1.html', board.views.popup),
    path('popup/event1.html', board.views.popup1),
    path('popup/event2.html', board.views.popup2),
    path('popup/event3.html', board.views.popup3),

    path('board/', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('login/', users.views.userlogin),
    path('logout/', users.views.userlogout),
    path('kakao_logout', users.views.kakao_logout),
    path('signup/', users.views.signup),

    path('mypage/', include('users.urls')),
    path('board/', include('board.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('shop/', include('shop.urls')),



    # path('question/', board.views.q_index, name='q_index'),
    # path('question/<int:question_id>', board.views.detail, name='detail'),
    # path('answer/create/<int:question_id>', board.views.answer_create, name='answer_create'),


]

board/models.py
from django.db import models
from users.models import User

# 1:1 문의
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

class Answer(models.Model):
    # author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

# 공지사항
class Notice(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

class N_comment(models.Model):
    # author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Notice, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

board/forms.py
from django import forms
from board.models import Question, Answer, Notice, N_comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

# create_date 속성은 데이터 저장 시점에 생성해야 하는 값이므로 QuestionForm에 등록하여 사용하지 않는다.

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice  # 사용할 모델
        fields = ['subject', 'content']  # NoticeForm에서 사용할 Notice 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

# create_date 속성은 데이터 저장 시점에 생성해야 하는 값이므로 NoticeForm에 등록하여 사용하지 않는다.

class N_commentForm(forms.ModelForm):
    class Meta:
        model = N_comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

board/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from cart.forms import AddProductForm
from shop.models import Product
from .models import Question, Answer, Notice, N_comment
from .forms import QuestionForm, AnswerForm, N_commentForm, NoticeForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# 메인페이지
def home(request):
    products = Product.objects.filter(available_display=True)
    add_to_cart = AddProductForm(initial={'quantity': 1})
    return render(request, 'home/mainpage.html', {'products':products,'add_to_cart':add_to_cart})

# 카테고리 팝업
def popup(request):
    return render(request, 'popup/popup1.html')

# 이벤트 팝업
def popup1(request):
    return render(request, 'popup/event1.html')

def popup2(request):
    return render(request, 'popup/event2.html')

def popup3(request):
    return render(request, 'popup/event3.html')

# 게시판 목록 출력
def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'board/question_list.html', context)

# 게시판 내용 출력
def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'board/question_detail.html', context)

# 답변 등록
@login_required(login_url='user:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'board/question_detail.html', context)

# 질문 등록
@login_required(login_url='user:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST) # request.POST에는 화면에서 사용자가 입력한 내용들이 담겨있다.
        if form.is_valid(): # 폼이 유효하다면
            question = form.save(commit=False) # 임시 저장하여 question 객체를 리턴받는다.
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now() # 실제 저장을 위해 작성일시를 설정한다.
            question.save()  # 데이터를 실제로 저장한다.
            return redirect('board:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 페이징
def index(request):
    #입력인자
    page = request.GET.get('page', '1')  # 페이지
    #조회
    question_list = Question.objects.order_by('-create_date')
    #페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj} # question_list는 페이징 객체(page_obj)
    return render(request, 'board/question_list.html', context)

# 질문 수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('board:detail', question_id=question.id)
    question.delete()
    return redirect('board:index')

# 답변 수정
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('board:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'board/answer_form.html', context)

# 답변 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

#--------------------------------------------------------------------------
# 게시판 목록 출력
def n_index(request):
    notice_list = Notice.objects.order_by('-create_date')
    context = {'notice_list': notice_list}
    return render(request, 'board/notice_list.html', context)

# 게시판 내용 출력
def n_detail(request, notice_id):
    notice = Notice.objects.get(id=notice_id)
    context = {'notice': notice}
    return render(request, 'board/notice_detail.html', context)

# 답변 등록
@login_required(login_url='user:login')
def n_answer_create(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if request.method == "POST":
        form = N_commentForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = notice
            answer.save()
            return redirect('board:n_detail', notice_id=notice.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'notice': notice, 'form': form}
    print(notice)
    return render(request, 'board/notice_detail.html', context)

# 공지 등록
@login_required(login_url='user:login')
def n_question_create(request):
    if request.method == 'POST':
        form = NoticeForm(request.POST) # request.POST에는 화면에서 사용자가 입력한 내용들이 담겨있다.
        if form.is_valid(): # 폼이 유효하다면
            notice = form.save(commit=False) # 임시 저장하여 question 객체를 리턴받는다.
            notice.author = request.user  # author 속성에 로그인 계정 저장
            notice.create_date = timezone.now() # 실제 저장을 위해 작성일시를 설정한다.
            notice.save()  # 데이터를 실제로 저장한다.
            return redirect('board:n_index')
    else:
        form = NoticeForm()
    context = {'form': form}
    return render(request, 'board/notice_form.html', context)

# 페이징
def n_index(request):
    #입력인자
    page = request.GET.get('page', '1')  # 페이지
    #조회
    notice_list = Notice.objects.order_by('-create_date')
    #페이징처리
    paginator = Paginator(notice_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'notice_list': page_obj} # notice_list는 페이징 객체(page_obj)
    return render(request, 'board/notice_list.html', context)

# 공지 수정
@login_required(login_url='common:login')
def n_question_modify(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if request.user != notice.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:n_detail', notice_id=notice_id)
    if request.method == "POST":
        form = NoticeForm(request.POST, instance=notice)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.modify_date = timezone.now()  # 수정일시 저장
            notice.save()
            return redirect('board:n_detail', notice_id=notice_id)
    else:
        form = NoticeForm(instance=notice)
    context = {'form': form}
    return render(request, 'board/notice_form.html', context)

# 공지 삭제
@login_required(login_url='common:login')
def n_question_delete(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if request.user != notice.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('board:detail', notice_id=notice.id)
    notice.delete()
    return redirect('board:n_index')

# 답변 수정
@login_required(login_url='common:login')
def n_answer_modify(request, n_comment_id):
    answer = get_object_or_404(N_comment, pk=n_comment_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:n_detail', n_answer_id=answer.notice.id)
    if request.method == "POST":
        form = N_commentForm(request.POST, instance=answer)
        if form.is_valid():
            n_comment = form.save(commit=False)
            n_comment.modify_date = timezone.now()
            n_comment.save()
            return redirect('board:n_detail', notice_id=n_comment.question.id)
    else:
        form = N_commentForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'board/n_comment_form.html', context)

# 답변 삭제
@login_required(login_url='common:login')
def n_answer_delete(request, n_comment_id):
    n_answer = get_object_or_404(N_comment, pk=n_comment_id)
    if request.user != n_answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        n_answer.delete()

templates/board/answer_form.html
{% extends 'home/base.html' %}
{% block body %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/n_comment_form.html
{% extends 'home/base.html' %}
{% block body %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/notice_detail.html
{% extends 'home/base.html' %}
{% block body %}
{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<div class="container my-3">
        <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ notice.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ notice.content }}</div>
            <div class="d-flex justify-content-end">
<!--                질문수정일시 표시하기-->
                {% if notice.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ notice.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{ notice.author.username }}</div>
                <div>{{ notice.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == notice.author %}
                <a href="{% url 'board:notice_modify' notice.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'board:notice_delete' notice.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
<!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{ notice.n_comment_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in notice.n_comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
<!--                답변수정일시 표시하기-->
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정됨</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{ notice.author.username }}</div>
                <div>{{ notice.create_date }}</div>
<!--                답변수정버튼-->
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                <a href="{% url 'board:n_answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
<!--                답변삭제버튼-->
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'board:n_answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'board:n_answer_create' notice.id %}" method="post" class="my-3">
        {% csrf_token %}
 <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
<!--        <div class="form-group">-->
<!--            <textarea name="content" id="content" class="form-control" rows="10"></textarea>-->
<!--        </div>-->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
</div>
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/board/notice_form.html
{% extends 'home/base.html' %}
{% block body %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<div class="container">
    <h5 class="my-3 border-bottom pb-2">공지사항</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/question_detail.html
{% extends 'home/base.html' %}
{% block body %}
{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<div class="container my-3">
        <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
<!--                질문수정일시 표시하기-->
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{ question.author.username }}</div>
                <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == question.author %}
                <a href="{% url 'board:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'board:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
<!--                답변수정일시 표시하기-->
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정됨</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{ question.author.username }}</div>
                <div>{{ question.create_date }}</div>
<!--                답변수정버튼-->
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                <a href="{% url 'board:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
<!--                답변삭제버튼-->
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'board:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
 <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
<!--        <div class="form-group">-->
<!--            <textarea name="content" id="content" class="form-control" rows="10"></textarea>-->
<!--        </div>-->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/board/question_form.html
{% extends 'home/base.html' %}
{% block body %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}